service: severless-ws-test

provider:
  name: aws
  runtime: nodejs10.x
  websocketsApiName: custom-websockets-api-name
  websocketsApiRouteSelectionExpression: $request.body.action
  profile: stepfunctions-user
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:*"
        - "s3:*"
      Resource:
        - "*"

functions:
  connectionHandler:
    handler: handler.connectionHandler
    events: 
      - websocket: 
          route: $connect
      - webssocket: 
          route: $disconnect
  defaultHandler: 
    handler: handler.defaultHandler
    events: 
      - websocket: $default
